spring.application.name=playlist-backend

server.address=0.0.0.0
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:h2:file:./data/mpp-playlists;MODE=PostgreSQL;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,http://192.168.8.230:5173
spring.data.mongodb.uri=mongodb://localhost:27017/mpp_chat
spring.data.mongodb.auto-index-creation=true
